### PR TITLE
Add Rails 7 Support

### PR DESCRIPTION
**Pull request by mbell697**
Hello and thank you for this library! 

This PR adds support for Rails 7.  I tried to minimize changes but it did require a couple tweaks to the dev environment in order to support Rails 7. For example the `.ruby-version` needed to be brought up since Rails 7 require Ruby >2.7. 

In terms of code - I only needed to change a single version check to get all tests to pass, I also pulled this check out to a constant for a nice little performance boost and future proofing. 

I saw in another PR that there are some issues with Travis - been there :) I'm happy to open a separate PR to move this repo over to use Github Actions assuming it's setup for the repo and that is the direction you'd like to go.

Cheers!

### CODE REVIEW

**Comment by GeorgeKaraszi** [comment]
Hey @mbell697 ! Thanks for taking a crack at Rails 7 compatibility. And yes Travis has finally bitten the bullet. If you've got the experience dealing with Github Actions, I welcome the changes to get it up and running. Always nice to see if changes break backwards compatibility 😉.

**Comment by DanAndreasson** [comment]
Was there any progress on this? :)

**Comment by mbell697** [comment]
I've updated this PR with the following:

1) Moved to 7.0 final in place of rc1

2) Added Github Actions based testing, including up through Ruby 3.1. @GeorgeKaraszi I believe you'll need to enable this on this repo  but you can see example output on our fork here: https://github.com/swoop-inc/ActiveRecordExtended/runs/4844805512?check_suite_focus=true

3) It looks like Rails 5.1/5.2 do not get along with Ruby 3.0/3.1 for reasons unrelated to the gem, thought I didn't dig in too deeply. I've excluded those combos from the test.

4) I pull in my change to the test suite switching to transaction based cleaning.  Normally I'd keep this as a separate PR but in this case it made testing so much faster that I likely wouldn't have had time to get CI testing working without it. 

5) I had to rework the `db:create` and `db:drop` rake tasks to get this working. Previously they were shelling out to `createdb` and `dropdb` which was making assumption about the database connection. Now it uses Rails internals. This was a bit wonky to get working across versions but it seems ok now. Perhaps in the future this `Rackfile` could be refactors to avoid duplication but I'll leave that as future work. 

I think this PR is now good to merge for Rails 7 / Ruby 3.0/3.1 support.

Cheers!

**Comment by GeorgeKaraszi** [comment]
This look good! ... Thank you for your hard work on this @mbell697 ... I will plan for a new release this week.

**Pull request merged**
