### PR TITLE
feat: add support for combining relations with IN

### PR DESCRIPTION
**Pull request by olafura**
By default ActiveRecord combines different where statements with an AND statement. This makes it hard to write scopes that can be combined without doing a lot of trickery.

### CODE REVIEW

**Comment by olafura** [comment]
@GeorgeKaraszi Let me know if you need me to rework it so it fits better into your library's structure.

**Comment by olafura** [comment]
@GeorgeKaraszi If you feel like this doesn't belong in your library let me know

**Comment by GeorgeKaraszi** [comment]
@olafura Thank you for your patience; this has been long overdue.

There are two issues I foresee with this feature:
1. Ideally, you shouldn't be in a situation where this would be useful. It has all the signs of a code base full of smells when you can't conjure up all your conditions beforehand, and you need to reach for a perplexing conditional modifier.
1. The feature doesn't fit into the ecosystem. The central aspect of this was to deliver hidden or non-implemented Postgres features into the ActiveRecord DSL.

**Comment by olafura** [comment]
@GeorgeKaraszi, sorry for the late reply. I got sick twice in the meantime.

It makes perfect sense that it doesn't fit. I was worried about that myself. Was just going to create a small gem but was starting to borrow a lot of the scaffolding ( Gemfile and Rakefile structure ) from your project. So, I thought I might just try it out as a PR.

I'll just create a small gem for this like I initially meant to do.

**Pull request closed without merging**
